/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as SignRouteImport } from './routes/sign'
import { Route as AuthedAppRouteImport } from './routes/_authed/_app'
import { Route as AuthedAdminRouteRouteImport } from './routes/_authed/admin/route'
import { Route as AuthedSettingsRouteRouteImport } from './routes/_authed/settings/route'
import { Route as AuthedAppIndexRouteImport } from './routes/_authed/_app/index'
import { Route as AuthedAppBotRouteImport } from './routes/_authed/_app/bot'
import { Route as AuthedAppSkillsRouteImport } from './routes/_authed/_app/skills'
import { Route as AuthedAdminIndexRouteImport } from './routes/_authed/admin/index'
import { Route as AuthedAdminAuditRouteImport } from './routes/_authed/admin/audit'
import { Route as AuthedAdminBoundariesRouteImport } from './routes/_authed/admin/boundaries'
import { Route as AuthedAdminComponentsRouteImport } from './routes/_authed/admin/components'
import { Route as AuthedAdminComputersRouteImport } from './routes/_authed/admin/computers'
import { Route as AuthedAdminConnectorsRouteImport } from './routes/_authed/admin/connectors'
import { Route as AuthedAdminCredentialsRouteImport } from './routes/_authed/admin/credentials'
import { Route as AuthedAdminPlaygroundRouteImport } from './routes/_authed/admin/playground'
import { Route as AuthedAdminPluginsRouteImport } from './routes/_authed/admin/plugins'
import { Route as AuthedSettingsIndexRouteImport } from './routes/_authed/settings/index'
import { Route as AuthedAppAgentsIndexRouteImport } from './routes/_authed/_app/agents/index'
import { Route as AuthedAppChannelChannelIdRouteImport } from './routes/_authed/_app/channel/$channelId'
import { Route as AuthedAppChannelNewRouteImport } from './routes/_authed/_app/channel/new'
import { Route as AuthedAdminConnectorsGoogleDriveRouteImport } from './routes/_authed/admin/connectors/google-drive'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const SignRoute = SignRouteImport.update({
  id: '/sign',
  path: '/sign',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAppRoute = AuthedAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRouteRoute = AuthedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRouteRoute = AuthedSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAppIndexRoute = AuthedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppBotRoute = AuthedAppBotRouteImport.update({
  id: '/bot',
  path: '/bot',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppSkillsRoute = AuthedAppSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAdminIndexRoute = AuthedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminAuditRoute = AuthedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminBoundariesRoute = AuthedAdminBoundariesRouteImport.update({
  id: '/boundaries',
  path: '/boundaries',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminComponentsRoute = AuthedAdminComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminComputersRoute = AuthedAdminComputersRouteImport.update({
  id: '/computers',
  path: '/computers',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminConnectorsRoute = AuthedAdminConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminCredentialsRoute = AuthedAdminCredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminPlaygroundRoute = AuthedAdminPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminPluginsRoute = AuthedAdminPluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedSettingsIndexRoute = AuthedSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedSettingsRouteRoute,
} as any)
const AuthedAppAgentsIndexRoute = AuthedAppAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppChannelChannelIdRoute =
  AuthedAppChannelChannelIdRouteImport.update({
    id: '/channel/$channelId',
    path: '/channel/$channelId',
    getParentRoute: () => AuthedAppRoute,
  } as any)
const AuthedAppChannelNewRoute = AuthedAppChannelNewRouteImport.update({
  id: '/channel/new',
  path: '/channel/new',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAdminConnectorsGoogleDriveRoute =
  AuthedAdminConnectorsGoogleDriveRouteImport.update({
    id: '/google-drive',
    path: '/google-drive',
    getParentRoute: () => AuthedAdminConnectorsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedAppIndexRoute
  '/sign': typeof SignRoute
  '/admin': typeof AuthedAdminRouteRouteWithChildren
  '/settings': typeof AuthedSettingsRouteRouteWithChildren
  '/bot': typeof AuthedAppBotRoute
  '/skills': typeof AuthedAppSkillsRoute
  '/admin/audit': typeof AuthedAdminAuditRoute
  '/admin/boundaries': typeof AuthedAdminBoundariesRoute
  '/admin/components': typeof AuthedAdminComponentsRoute
  '/admin/computers': typeof AuthedAdminComputersRoute
  '/admin/connectors': typeof AuthedAdminConnectorsRouteWithChildren
  '/admin/credentials': typeof AuthedAdminCredentialsRoute
  '/admin/playground': typeof AuthedAdminPlaygroundRoute
  '/admin/plugins': typeof AuthedAdminPluginsRoute
  '/admin/': typeof AuthedAdminIndexRoute
  '/settings/': typeof AuthedSettingsIndexRoute
  '/channel/$channelId': typeof AuthedAppChannelChannelIdRoute
  '/channel/new': typeof AuthedAppChannelNewRoute
  '/admin/connectors/google-drive': typeof AuthedAdminConnectorsGoogleDriveRoute
  '/agents/': typeof AuthedAppAgentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthedAppIndexRoute
  '/sign': typeof SignRoute
  '/bot': typeof AuthedAppBotRoute
  '/skills': typeof AuthedAppSkillsRoute
  '/admin/audit': typeof AuthedAdminAuditRoute
  '/admin/boundaries': typeof AuthedAdminBoundariesRoute
  '/admin/components': typeof AuthedAdminComponentsRoute
  '/admin/computers': typeof AuthedAdminComputersRoute
  '/admin/connectors': typeof AuthedAdminConnectorsRouteWithChildren
  '/admin/credentials': typeof AuthedAdminCredentialsRoute
  '/admin/playground': typeof AuthedAdminPlaygroundRoute
  '/admin/plugins': typeof AuthedAdminPluginsRoute
  '/admin': typeof AuthedAdminIndexRoute
  '/settings': typeof AuthedSettingsIndexRoute
  '/channel/$channelId': typeof AuthedAppChannelChannelIdRoute
  '/channel/new': typeof AuthedAppChannelNewRoute
  '/admin/connectors/google-drive': typeof AuthedAdminConnectorsGoogleDriveRoute
  '/agents': typeof AuthedAppAgentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/sign': typeof SignRoute
  '/_authed/admin': typeof AuthedAdminRouteRouteWithChildren
  '/_authed/settings': typeof AuthedSettingsRouteRouteWithChildren
  '/_authed/_app': typeof AuthedAppRouteWithChildren
  '/_authed/_app/bot': typeof AuthedAppBotRoute
  '/_authed/_app/skills': typeof AuthedAppSkillsRoute
  '/_authed/admin/audit': typeof AuthedAdminAuditRoute
  '/_authed/admin/boundaries': typeof AuthedAdminBoundariesRoute
  '/_authed/admin/components': typeof AuthedAdminComponentsRoute
  '/_authed/admin/computers': typeof AuthedAdminComputersRoute
  '/_authed/admin/connectors': typeof AuthedAdminConnectorsRouteWithChildren
  '/_authed/admin/credentials': typeof AuthedAdminCredentialsRoute
  '/_authed/admin/playground': typeof AuthedAdminPlaygroundRoute
  '/_authed/admin/plugins': typeof AuthedAdminPluginsRoute
  '/_authed/_app/': typeof AuthedAppIndexRoute
  '/_authed/admin/': typeof AuthedAdminIndexRoute
  '/_authed/settings/': typeof AuthedSettingsIndexRoute
  '/_authed/_app/channel/$channelId': typeof AuthedAppChannelChannelIdRoute
  '/_authed/_app/channel/new': typeof AuthedAppChannelNewRoute
  '/_authed/admin/connectors/google-drive': typeof AuthedAdminConnectorsGoogleDriveRoute
  '/_authed/_app/agents/': typeof AuthedAppAgentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign'
    | '/admin'
    | '/settings'
    | '/bot'
    | '/skills'
    | '/admin/audit'
    | '/admin/boundaries'
    | '/admin/components'
    | '/admin/computers'
    | '/admin/connectors'
    | '/admin/credentials'
    | '/admin/playground'
    | '/admin/plugins'
    | '/admin/'
    | '/settings/'
    | '/channel/$channelId'
    | '/channel/new'
    | '/admin/connectors/google-drive'
    | '/agents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign'
    | '/bot'
    | '/skills'
    | '/admin/audit'
    | '/admin/boundaries'
    | '/admin/components'
    | '/admin/computers'
    | '/admin/connectors'
    | '/admin/credentials'
    | '/admin/playground'
    | '/admin/plugins'
    | '/admin'
    | '/settings'
    | '/channel/$channelId'
    | '/channel/new'
    | '/admin/connectors/google-drive'
    | '/agents'
  id:
    | '__root__'
    | '/_authed'
    | '/sign'
    | '/_authed/admin'
    | '/_authed/settings'
    | '/_authed/_app'
    | '/_authed/_app/bot'
    | '/_authed/_app/skills'
    | '/_authed/admin/audit'
    | '/_authed/admin/boundaries'
    | '/_authed/admin/components'
    | '/_authed/admin/computers'
    | '/_authed/admin/connectors'
    | '/_authed/admin/credentials'
    | '/_authed/admin/playground'
    | '/_authed/admin/plugins'
    | '/_authed/_app/'
    | '/_authed/admin/'
    | '/_authed/settings/'
    | '/_authed/_app/channel/$channelId'
    | '/_authed/_app/channel/new'
    | '/_authed/admin/connectors/google-drive'
    | '/_authed/_app/agents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  SignRoute: typeof SignRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign': {
      id: '/sign'
      path: '/sign'
      fullPath: '/sign'
      preLoaderRoute: typeof SignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/_app': {
      id: '/_authed/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedAppRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_app/': {
      id: '/_authed/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedAppIndexRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/bot': {
      id: '/_authed/_app/bot'
      path: '/bot'
      fullPath: '/bot'
      preLoaderRoute: typeof AuthedAppBotRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/skills': {
      id: '/_authed/_app/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof AuthedAppSkillsRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/admin/': {
      id: '/_authed/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthedAdminIndexRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/audit': {
      id: '/_authed/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthedAdminAuditRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/boundaries': {
      id: '/_authed/admin/boundaries'
      path: '/boundaries'
      fullPath: '/admin/boundaries'
      preLoaderRoute: typeof AuthedAdminBoundariesRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/components': {
      id: '/_authed/admin/components'
      path: '/components'
      fullPath: '/admin/components'
      preLoaderRoute: typeof AuthedAdminComponentsRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/computers': {
      id: '/_authed/admin/computers'
      path: '/computers'
      fullPath: '/admin/computers'
      preLoaderRoute: typeof AuthedAdminComputersRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/connectors': {
      id: '/_authed/admin/connectors'
      path: '/connectors'
      fullPath: '/admin/connectors'
      preLoaderRoute: typeof AuthedAdminConnectorsRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/credentials': {
      id: '/_authed/admin/credentials'
      path: '/credentials'
      fullPath: '/admin/credentials'
      preLoaderRoute: typeof AuthedAdminCredentialsRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/playground': {
      id: '/_authed/admin/playground'
      path: '/playground'
      fullPath: '/admin/playground'
      preLoaderRoute: typeof AuthedAdminPlaygroundRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/plugins': {
      id: '/_authed/admin/plugins'
      path: '/plugins'
      fullPath: '/admin/plugins'
      preLoaderRoute: typeof AuthedAdminPluginsRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/settings/': {
      id: '/_authed/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthedSettingsIndexRouteImport
      parentRoute: typeof AuthedSettingsRouteRoute
    }
    '/_authed/_app/agents/': {
      id: '/_authed/_app/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AuthedAppAgentsIndexRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/channel/$channelId': {
      id: '/_authed/_app/channel/$channelId'
      path: '/channel/$channelId'
      fullPath: '/channel/$channelId'
      preLoaderRoute: typeof AuthedAppChannelChannelIdRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/channel/new': {
      id: '/_authed/_app/channel/new'
      path: '/channel/new'
      fullPath: '/channel/new'
      preLoaderRoute: typeof AuthedAppChannelNewRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/admin/connectors/google-drive': {
      id: '/_authed/admin/connectors/google-drive'
      path: '/google-drive'
      fullPath: '/admin/connectors/google-drive'
      preLoaderRoute: typeof AuthedAdminConnectorsGoogleDriveRouteImport
      parentRoute: typeof AuthedAdminConnectorsRoute
    }
  }
}

interface AuthedAdminConnectorsRouteChildren {
  AuthedAdminConnectorsGoogleDriveRoute: typeof AuthedAdminConnectorsGoogleDriveRoute
}

const AuthedAdminConnectorsRouteChildren: AuthedAdminConnectorsRouteChildren = {
  AuthedAdminConnectorsGoogleDriveRoute: AuthedAdminConnectorsGoogleDriveRoute,
}

const AuthedAdminConnectorsRouteWithChildren =
  AuthedAdminConnectorsRoute._addFileChildren(
    AuthedAdminConnectorsRouteChildren,
  )

interface AuthedAdminRouteRouteChildren {
  AuthedAdminAuditRoute: typeof AuthedAdminAuditRoute
  AuthedAdminBoundariesRoute: typeof AuthedAdminBoundariesRoute
  AuthedAdminComponentsRoute: typeof AuthedAdminComponentsRoute
  AuthedAdminComputersRoute: typeof AuthedAdminComputersRoute
  AuthedAdminConnectorsRoute: typeof AuthedAdminConnectorsRouteWithChildren
  AuthedAdminCredentialsRoute: typeof AuthedAdminCredentialsRoute
  AuthedAdminPlaygroundRoute: typeof AuthedAdminPlaygroundRoute
  AuthedAdminPluginsRoute: typeof AuthedAdminPluginsRoute
  AuthedAdminIndexRoute: typeof AuthedAdminIndexRoute
}

const AuthedAdminRouteRouteChildren: AuthedAdminRouteRouteChildren = {
  AuthedAdminAuditRoute: AuthedAdminAuditRoute,
  AuthedAdminBoundariesRoute: AuthedAdminBoundariesRoute,
  AuthedAdminComponentsRoute: AuthedAdminComponentsRoute,
  AuthedAdminComputersRoute: AuthedAdminComputersRoute,
  AuthedAdminConnectorsRoute: AuthedAdminConnectorsRouteWithChildren,
  AuthedAdminCredentialsRoute: AuthedAdminCredentialsRoute,
  AuthedAdminPlaygroundRoute: AuthedAdminPlaygroundRoute,
  AuthedAdminPluginsRoute: AuthedAdminPluginsRoute,
  AuthedAdminIndexRoute: AuthedAdminIndexRoute,
}

const AuthedAdminRouteRouteWithChildren =
  AuthedAdminRouteRoute._addFileChildren(AuthedAdminRouteRouteChildren)

interface AuthedSettingsRouteRouteChildren {
  AuthedSettingsIndexRoute: typeof AuthedSettingsIndexRoute
}

const AuthedSettingsRouteRouteChildren: AuthedSettingsRouteRouteChildren = {
  AuthedSettingsIndexRoute: AuthedSettingsIndexRoute,
}

const AuthedSettingsRouteRouteWithChildren =
  AuthedSettingsRouteRoute._addFileChildren(AuthedSettingsRouteRouteChildren)

interface AuthedAppRouteChildren {
  AuthedAppBotRoute: typeof AuthedAppBotRoute
  AuthedAppSkillsRoute: typeof AuthedAppSkillsRoute
  AuthedAppIndexRoute: typeof AuthedAppIndexRoute
  AuthedAppChannelChannelIdRoute: typeof AuthedAppChannelChannelIdRoute
  AuthedAppChannelNewRoute: typeof AuthedAppChannelNewRoute
  AuthedAppAgentsIndexRoute: typeof AuthedAppAgentsIndexRoute
}

const AuthedAppRouteChildren: AuthedAppRouteChildren = {
  AuthedAppBotRoute: AuthedAppBotRoute,
  AuthedAppSkillsRoute: AuthedAppSkillsRoute,
  AuthedAppIndexRoute: AuthedAppIndexRoute,
  AuthedAppChannelChannelIdRoute: AuthedAppChannelChannelIdRoute,
  AuthedAppChannelNewRoute: AuthedAppChannelNewRoute,
  AuthedAppAgentsIndexRoute: AuthedAppAgentsIndexRoute,
}

const AuthedAppRouteWithChildren = AuthedAppRoute._addFileChildren(
  AuthedAppRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAdminRouteRoute: typeof AuthedAdminRouteRouteWithChildren
  AuthedSettingsRouteRoute: typeof AuthedSettingsRouteRouteWithChildren
  AuthedAppRoute: typeof AuthedAppRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRouteRoute: AuthedAdminRouteRouteWithChildren,
  AuthedSettingsRouteRoute: AuthedSettingsRouteRouteWithChildren,
  AuthedAppRoute: AuthedAppRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  SignRoute: SignRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
