import { mkdir, writeFile } from "node:fs/promises";
import { dirname, isAbsolute, resolve } from "node:path";
import {
  createApplicationConfiguration,
  loadTenantPackage,
} from "../server/src/tenant-package";

const projectRoot = resolve(import.meta.dir, "..");
const configuredTenantPackageDirectory = process.env.TENANT_PACKAGE_DIR;
const tenantPackageDirectory = configuredTenantPackageDirectory
  ? isAbsolute(configuredTenantPackageDirectory)
    ? configuredTenantPackageDirectory
    : resolve(projectRoot, "server", configuredTenantPackageDirectory)
  : resolve(projectRoot, "examples/fintech");
const tenantPackage = await loadTenantPackage(tenantPackageDirectory);
const providers =
  process.env.GOOGLE_OAUTH_CLIENT_ID?.trim() &&
  process.env.GOOGLE_OAUTH_CLIENT_SECRET?.trim() &&
  process.env.BETTER_AUTH_SECRET?.trim() &&
  process.env.BETTER_AUTH_URL?.trim()
    ? ["google"]
    : [];
const applicationConfiguration = createApplicationConfiguration(
  tenantPackage,
  providers,
);
const outputPath = resolve(
  projectRoot,
  "app/src/lib/generated/application-config.ts",
);

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(
  outputPath,
  [
    "// This file is generated by scripts/generate-app-config.ts. Do not edit it.",
    "export type AppConfig = { brand: { tenantId: string; productName: string }; auth: { providers: readonly string[] } };",
    `export const appConfig: AppConfig = ${JSON.stringify(applicationConfiguration, null, 2)};`,
    "",
  ].join("\n"),
);
